"""GOAL-6 — the WF gate's admission scope is BOOSTER-BLIND, executed rather than read.

WHY THIS FILE EXISTS
--------------------
On the production path `strategy_config.walkforward.enabled` is true, and
`runner.inspect_artifact_usage` returns `candidate_artifact_used: False`
**unconditionally** there — a current artifact cannot be replayed into old sim
windows without look-ahead, so the gate validates the retraining *recipe* instead.

Admission scope is then decided by

    validation_scope_ok = candidate_artifact_used or recipe_validated
                        = False                  or recipe_validated

so on the production path admission rides **entirely** on `recipe_validated`.

And `recipe_projection` — the thing the fingerprint is taken over — contains
`kind`, `feature_cols`, `feature_norm_kind`, the feature-source contract KEYS,
`label_col`, `lookahead_days` and the semantic learner params.  **It contains no
learned parameter.**  Two artifacts trained from the same recipe on different data,
or to different quality, therefore carry the *same* fingerprint.

The consequence, which these tests execute rather than assert in prose: a candidate
booster is admitted in scope on evidence generated by a **different** booster, and
no gate anywhere in this path scores the candidate's own weights.

These are CHARACTERISATION tests.  They pin the behaviour that is in force today so
it cannot change silently.  **They do not endorse it** — the gap they describe is
what blocks GOAL-6's evaluation path and GOAL-4's ensemble admission alike.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from renquant_backtesting.wf_gate.recipe_match import (
    manifest_recipe_usage,
    recipe_fingerprint,
    recipe_projection,
)


def _artifact(booster: str, *, features=("f1", "f2", "f3"), kind="panel_ltr_xgboost",
              lookahead=60, params=None) -> dict:
    """A minimal artifact whose recipe fields are explicit and whose learned
    payload (`booster`) is the ONLY thing varied between the two candidates."""
    return {
        "kind": kind,
        "feature_cols": list(features),
        "feature_norm_kind": ["zscore"] * len(features),
        "feature_source_contract": {"raw": "prose that may be edited", "panel": "…"},
        "label_col": "fwd_60d_excess",
        "lookahead_days": lookahead,
        "params": params or {"eta": 0.05, "max_depth": 4, "seed": 7},
        # everything below is the LEARNED payload — not in recipe_projection
        "booster": booster,
        "trained_date": "2026-07-30",
        "n_trees": 400,
    }


def _write(tmp: Path, name: str, payload: dict) -> Path:
    p = tmp / name
    p.write_text(json.dumps(payload), encoding="utf-8")
    return p


def _manifest(tmp: Path, artifact_paths, name="walkforward_manifest.json") -> Path:
    p = tmp / name
    p.write_text(json.dumps(
        {"retrains": [{"artifact_uri": str(a)} for a in artifact_paths]}),
        encoding="utf-8")
    return p


# ------------------------------------------------------- the projection ------
def test_recipe_projection_contains_no_learned_parameter():
    """The fingerprint's inputs, enumerated. If a learned field ever enters this
    set the tests below stop describing the system and this one fails first."""
    proj = recipe_projection(_artifact("anything"))
    assert set(proj) == {
        "kind", "feature_cols", "feature_norm_kind",
        "feature_source_contract_keys", "label_col", "lookahead_days", "params",
    }
    flat = json.dumps(proj)
    assert "booster" not in flat
    assert "n_trees" not in flat
    assert "trained_date" not in flat


def test_two_boosters_from_one_recipe_share_a_fingerprint():
    good = _artifact("BOOSTER-TRAINED-ON-REAL-LABELS")
    junk = _artifact("BOOSTER-TRAINED-ON-SHUFFLED-LABELS")
    assert good["booster"] != junk["booster"]
    assert recipe_fingerprint(good) == recipe_fingerprint(junk)


def test_prose_edits_to_the_source_contract_do_not_move_the_fingerprint():
    """Behavioural anchor 2026-05-27 — keys are hashed, values are not."""
    a = _artifact("b")
    b = _artifact("b")
    b["feature_source_contract"] = {"raw": "COMPLETELY DIFFERENT PROSE", "panel": "x"}
    assert recipe_fingerprint(a) == recipe_fingerprint(b)


# ------------------------------------------- admission on the WF path --------
def test_a_different_booster_is_admitted_on_another_boosters_evidence(tmp_path):
    """The headline. The manifest contains artifact A; the CANDIDATE is B."""
    a = _write(tmp_path, "a.json", _artifact("BOOSTER-A"))
    b = _write(tmp_path, "b.json", _artifact("BOOSTER-B"))
    man = _manifest(tmp_path, [a])

    usage = manifest_recipe_usage(man, b, strategy_dir=tmp_path)
    assert usage["recipe_validated"] is True

    # …and this is what the runner then computes, verbatim:
    candidate_artifact_used = False          # hardcoded on the walkforward path
    validation_scope_ok = candidate_artifact_used or bool(usage["recipe_validated"])
    assert validation_scope_ok is True


@pytest.mark.parametrize("mutate", [
    lambda a: a.update(feature_cols=["f1", "f2"]),          # dropped a feature
    lambda a: a.update(kind="hf_patchtst"),                 # different model kind
    lambda a: a.update(lookahead_days=20),                  # different label horizon
    lambda a: a.update(params={"eta": 0.30, "max_depth": 4, "seed": 7}),
])
def test_a_genuinely_different_RECIPE_is_refused(tmp_path, mutate):
    """ANTI-VACUITY. Without this, a `recipe_validated` that is hardcoded True
    would pass the headline test and the file would prove nothing."""
    a = _write(tmp_path, "a.json", _artifact("BOOSTER-A"))
    cand = _artifact("BOOSTER-B")
    mutate(cand)
    b = _write(tmp_path, "b.json", cand)
    man = _manifest(tmp_path, [a])

    usage = manifest_recipe_usage(man, b, strategy_dir=tmp_path)
    assert usage["recipe_validated"] is False
    assert not (False or bool(usage["recipe_validated"]))


def test_one_mismatching_sample_refuses_the_whole_manifest(tmp_path):
    """`all_match` — a single divergent manifest row must sink admission."""
    same = _write(tmp_path, "same.json", _artifact("BOOSTER-A"))
    other = _artifact("BOOSTER-C")
    other["feature_cols"] = ["f1"]
    diff = _write(tmp_path, "diff.json", other)
    man = _manifest(tmp_path, [same, diff])
    usage = manifest_recipe_usage(man, same, strategy_dir=tmp_path)
    assert usage["recipe_validated"] is False


def test_a_missing_manifest_artifact_is_a_refusal_not_a_skip(tmp_path):
    a = _write(tmp_path, "a.json", _artifact("BOOSTER-A"))
    man = _manifest(tmp_path, [tmp_path / "does-not-exist.json"])
    usage = manifest_recipe_usage(man, a, strategy_dir=tmp_path)
    assert usage["recipe_validated"] is False


def test_an_absent_manifest_is_a_refusal_not_a_skip(tmp_path):
    a = _write(tmp_path, "a.json", _artifact("BOOSTER-A"))
    usage = manifest_recipe_usage(tmp_path / "nope.json", a, strategy_dir=tmp_path)
    assert usage["recipe_validated"] is False


def test_an_empty_manifest_is_a_refusal_not_a_skip(tmp_path):
    a = _write(tmp_path, "a.json", _artifact("BOOSTER-A"))
    man = tmp_path / "m.json"
    man.write_text(json.dumps({"retrains": []}), encoding="utf-8")
    usage = manifest_recipe_usage(man, a, strategy_dir=tmp_path)
    assert usage["recipe_validated"] is False


def test_the_reported_fingerprint_is_the_candidates_own(tmp_path):
    """So a reader of the gate's metadata can reproduce the comparison."""
    payload = _artifact("BOOSTER-A")
    a = _write(tmp_path, "a.json", payload)
    man = _manifest(tmp_path, [a])
    usage = manifest_recipe_usage(man, a, strategy_dir=tmp_path)
    assert usage["candidate_recipe_fingerprint"] == recipe_fingerprint(payload)
    assert usage["manifest_rows_checked"] == 1
